appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WiT7VJdBwU6NQoOwRXS22mV3n8VrGupBa/s4/tQAlwN3vzRzuh3m78I5CcwNAQeyuEc0RY4S9lybjYpxMaXnpmKQzY/8KljlmP2AsYDNYIWinrw6SWu6kBsGjLBxq5ALvy/5pwUDuFgC7Be7vki3P3sGR6WwaAD1EblXsJ+JFSiS453qRum88okizZTmgtUMkav0nGUAfCYuIPu0mzYGIANwba1PTy9BofnkyRtOkPIr3dMKJnoGAzVWCDb1GU5YaaKn3h5itY5o+trwaGBrCuSpdYbRJw++iw+q03me0IE+2e7So+l4T1JubLqiXIFrb2foI5/uxgu0WIqD7MYwLZS63UxOqIEk55EjEoKM02PCpWQHxFUzO8c8qZrTMRNm7gy/Irc2t6z6LBgDyblSaWza8tHyu20k0RKVcHfqDaZdF4kxpYdBYyC1gS7YgACT4c3NaTSUfc2elfrLiUbg6MGCgRpvs0cCvDgfQiGI4et0H/TSOr6XB7d5ifrukIKgp+5/3XqvHr/ErTDVKmw81JSJ3KhlzxzPsT8QW/eNwJtKbHcZ43OFu/4/NsYffwjeuSmJKIhuMwKWronziohw/qku2r0Vs+U/huZ+mjWMue2baU5tE/I3+WqGghCsah6Ige+MxBAtFqtV1GqTWzZ5CKcrjKX3gP9Ov5kY2/yN//Y=}
conda_forge_output_validation: true
