travis:
  secure:
    BINSTAR_TOKEN: S/g3Fn2/aOQ0ZyZWk2eNLB8NxFisc+l03fjaJbu2gTNlUw78eFXk+aeJs+B4W6n5J40zQT+X65Q4AePscGTZyh7gkxeJhBhkAGHBhn7cUlTV5TcfWAsfOZQK1u5oQsKe+ja5kmPg6OWtcxa4FDCmfkAgS42vIkWcG/Nsu5nLS2p2xvqAv8ZuhJ9zk/432+T7LcukmxEsmzZIJTMFM9ti9tRB1wDIqzV2MARsz5uJMiokiF7V7wU0y6tCSUBDhZSJx+CIUj3Sf3n0JXounQDEL5M7zSgOa0fxeCnZicCBNJlUKDIxLpRt3VeAaHfI+Mh5r+ro9+H+eja0nudDL2yy4VIz/Y4r/4HxZlbXgfscENjUnUf4nDqmIuguLWrGxa0UOSx+/AbiFnMd9B9QYpiOUC1Kd+Kf5+7abBO6Ftt0fCgR2gA17RuLr+CYEiidM+K5NGhe+msH6KvykQmklFHJvTYElOkKcNTtRQ/s77mcBuE3hbKwuBE7PsFx0LjhI9mWqLtcf9wNk/UatCBuzrdtrImSTsdWK3Qx7GK2DXf4EkDJEog6lHM1uwcdNN0S3c5mq+xVcUJS2PsfLfORxnw7GTZv7w7VCxNJ44UOA7Vs0zUpNhuv1XMdvB1xqEfhmgWoWe7xVKAHBxPecqxTOOCMXAPwFZx/GAYHjbUqTg+sfWk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
